# Generated by Django 5.1 on 2024-09-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='is_show_on_home_page',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
