# Generated by Django 5.1 on 2025-04-20 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='WebAdmin.photogallerycategories'),
        ),
    ]
