# Generated by Django 5.1 on 2024-09-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdmin', '0002_photogallery_is_show_on_home_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='is_show_on_home_page',
            field=models.BooleanField(null=True),
        ),
    ]
