# Generated by Django 5.1 on 2024-09-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdmin', '0003_alter_photogallery_is_show_on_home_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('posted_on', models.DateField()),
                ('vacancy', models.IntegerField()),
                ('desired_qualification', models.TextField()),
                ('experience_required', models.TextField()),
                ('job_description', models.TextField()),
                ('roles_responsibility', models.TextField()),
                ('skills_required', models.TextField()),
            ],
        ),
    ]
