# Generated by Django 5.1 on 2024-09-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdmin', '0004_career'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Career',
            new_name='Job',
        ),
    ]
