# Generated by Django 5.1 on 2024-09-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdmin', '0006_career_delete_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='posted_on',
            field=models.DateField(auto_now=True),
        ),
    ]
