# Generated by Django 5.1 on 2024-09-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdmin', '0008_careerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
