# Generated by Django 5.1 on 2024-09-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdmin', '0009_career_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='is_public',
            new_name='is_publish',
        ),
    ]
