# Generated by Django 5.1 on 2024-09-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdmin', '0010_rename_is_public_career_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerapplication',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='posted_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
