# Generated by Django 5.1.1 on 2024-10-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdmin', '0013_enquiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.FileField(upload_to='video_gallery/')),
                ('is_show_on_home_page', models.BooleanField(null=True)),
            ],
        ),
    ]
