# Generated by Django 5.1 on 2024-10-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdmin', '0014_videogallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogallery',
            name='description',
        ),
        migrations.RemoveField(
            model_name='videogallery',
            name='is_show_on_home_page',
        ),
        migrations.RemoveField(
            model_name='videogallery',
            name='video',
        ),
        migrations.AddField(
            model_name='videogallery',
            name='video_link',
            field=models.CharField(blank=True, help_text='Enter YouTube video link', max_length=255, null=True),
        ),
    ]
